development:
  adapter: postgresql
  encoding: UTF-8
  database: notebrush_development
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: UTF-8
  database: notebrush_test
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: UTF-8
  database: notebrush_production
  host: localhost
  pool: 5
